// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: rendezvous.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnType int32

const (
	ConnType_DEFAULT_CONN  ConnType = 0
	ConnType_FILE_TRANSFER ConnType = 1
	ConnType_PORT_FORWARD  ConnType = 2
	ConnType_RDP           ConnType = 3
	ConnType_VIEW_CAMERA   ConnType = 4
	ConnType_TERMINAL      ConnType = 5
)

// Enum value maps for ConnType.
var (
	ConnType_name = map[int32]string{
		0: "DEFAULT_CONN",
		1: "FILE_TRANSFER",
		2: "PORT_FORWARD",
		3: "RDP",
		4: "VIEW_CAMERA",
		5: "TERMINAL",
	}
	ConnType_value = map[string]int32{
		"DEFAULT_CONN":  0,
		"FILE_TRANSFER": 1,
		"PORT_FORWARD":  2,
		"RDP":           3,
		"VIEW_CAMERA":   4,
		"TERMINAL":      5,
	}
)

func (x ConnType) Enum() *ConnType {
	p := new(ConnType)
	*p = x
	return p
}

func (x ConnType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnType) Descriptor() protoreflect.EnumDescriptor {
	return file_rendezvous_proto_enumTypes[0].Descriptor()
}

func (ConnType) Type() protoreflect.EnumType {
	return &file_rendezvous_proto_enumTypes[0]
}

func (x ConnType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnType.Descriptor instead.
func (ConnType) EnumDescriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{0}
}

type NatType int32

const (
	NatType_UNKNOWN_NAT NatType = 0
	NatType_ASYMMETRIC  NatType = 1
	NatType_SYMMETRIC   NatType = 2
)

// Enum value maps for NatType.
var (
	NatType_name = map[int32]string{
		0: "UNKNOWN_NAT",
		1: "ASYMMETRIC",
		2: "SYMMETRIC",
	}
	NatType_value = map[string]int32{
		"UNKNOWN_NAT": 0,
		"ASYMMETRIC":  1,
		"SYMMETRIC":   2,
	}
)

func (x NatType) Enum() *NatType {
	p := new(NatType)
	*p = x
	return p
}

func (x NatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NatType) Descriptor() protoreflect.EnumDescriptor {
	return file_rendezvous_proto_enumTypes[1].Descriptor()
}

func (NatType) Type() protoreflect.EnumType {
	return &file_rendezvous_proto_enumTypes[1]
}

func (x NatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NatType.Descriptor instead.
func (NatType) EnumDescriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{1}
}

type ControlPermissions_Permission int32

const (
	ControlPermissions_keyboard       ControlPermissions_Permission = 0
	ControlPermissions_remote_printer ControlPermissions_Permission = 1
	ControlPermissions_clipboard      ControlPermissions_Permission = 2
	ControlPermissions_file           ControlPermissions_Permission = 3
	ControlPermissions_audio          ControlPermissions_Permission = 4
	ControlPermissions_camera         ControlPermissions_Permission = 5
	ControlPermissions_terminal       ControlPermissions_Permission = 6
	ControlPermissions_tunnel         ControlPermissions_Permission = 7
	ControlPermissions_restart        ControlPermissions_Permission = 8
	ControlPermissions_recording      ControlPermissions_Permission = 9
	ControlPermissions_block_input    ControlPermissions_Permission = 10
	ControlPermissions_remote_modify  ControlPermissions_Permission = 11
)

// Enum value maps for ControlPermissions_Permission.
var (
	ControlPermissions_Permission_name = map[int32]string{
		0:  "keyboard",
		1:  "remote_printer",
		2:  "clipboard",
		3:  "file",
		4:  "audio",
		5:  "camera",
		6:  "terminal",
		7:  "tunnel",
		8:  "restart",
		9:  "recording",
		10: "block_input",
		11: "remote_modify",
	}
	ControlPermissions_Permission_value = map[string]int32{
		"keyboard":       0,
		"remote_printer": 1,
		"clipboard":      2,
		"file":           3,
		"audio":          4,
		"camera":         5,
		"terminal":       6,
		"tunnel":         7,
		"restart":        8,
		"recording":      9,
		"block_input":    10,
		"remote_modify":  11,
	}
)

func (x ControlPermissions_Permission) Enum() *ControlPermissions_Permission {
	p := new(ControlPermissions_Permission)
	*p = x
	return p
}

func (x ControlPermissions_Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlPermissions_Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_rendezvous_proto_enumTypes[2].Descriptor()
}

func (ControlPermissions_Permission) Type() protoreflect.EnumType {
	return &file_rendezvous_proto_enumTypes[2]
}

func (x ControlPermissions_Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlPermissions_Permission.Descriptor instead.
func (ControlPermissions_Permission) EnumDescriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{3, 0}
}

type RegisterPkResponse_Result int32

const (
	RegisterPkResponse_OK                RegisterPkResponse_Result = 0
	RegisterPkResponse_UUID_MISMATCH     RegisterPkResponse_Result = 2
	RegisterPkResponse_ID_EXISTS         RegisterPkResponse_Result = 3
	RegisterPkResponse_TOO_FREQUENT      RegisterPkResponse_Result = 4
	RegisterPkResponse_INVALID_ID_FORMAT RegisterPkResponse_Result = 5
	RegisterPkResponse_NOT_SUPPORT       RegisterPkResponse_Result = 6
	RegisterPkResponse_SERVER_ERROR      RegisterPkResponse_Result = 7
)

// Enum value maps for RegisterPkResponse_Result.
var (
	RegisterPkResponse_Result_name = map[int32]string{
		0: "OK",
		2: "UUID_MISMATCH",
		3: "ID_EXISTS",
		4: "TOO_FREQUENT",
		5: "INVALID_ID_FORMAT",
		6: "NOT_SUPPORT",
		7: "SERVER_ERROR",
	}
	RegisterPkResponse_Result_value = map[string]int32{
		"OK":                0,
		"UUID_MISMATCH":     2,
		"ID_EXISTS":         3,
		"TOO_FREQUENT":      4,
		"INVALID_ID_FORMAT": 5,
		"NOT_SUPPORT":       6,
		"SERVER_ERROR":      7,
	}
)

func (x RegisterPkResponse_Result) Enum() *RegisterPkResponse_Result {
	p := new(RegisterPkResponse_Result)
	*p = x
	return p
}

func (x RegisterPkResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterPkResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_rendezvous_proto_enumTypes[3].Descriptor()
}

func (RegisterPkResponse_Result) Type() protoreflect.EnumType {
	return &file_rendezvous_proto_enumTypes[3]
}

func (x RegisterPkResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterPkResponse_Result.Descriptor instead.
func (RegisterPkResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{9, 0}
}

type PunchHoleResponse_Failure int32

const (
	PunchHoleResponse_ID_NOT_EXIST     PunchHoleResponse_Failure = 0
	PunchHoleResponse_OFFLINE          PunchHoleResponse_Failure = 2
	PunchHoleResponse_LICENSE_MISMATCH PunchHoleResponse_Failure = 3
	PunchHoleResponse_LICENSE_OVERUSE  PunchHoleResponse_Failure = 4
)

// Enum value maps for PunchHoleResponse_Failure.
var (
	PunchHoleResponse_Failure_name = map[int32]string{
		0: "ID_NOT_EXIST",
		2: "OFFLINE",
		3: "LICENSE_MISMATCH",
		4: "LICENSE_OVERUSE",
	}
	PunchHoleResponse_Failure_value = map[string]int32{
		"ID_NOT_EXIST":     0,
		"OFFLINE":          2,
		"LICENSE_MISMATCH": 3,
		"LICENSE_OVERUSE":  4,
	}
)

func (x PunchHoleResponse_Failure) Enum() *PunchHoleResponse_Failure {
	p := new(PunchHoleResponse_Failure)
	*p = x
	return p
}

func (x PunchHoleResponse_Failure) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PunchHoleResponse_Failure) Descriptor() protoreflect.EnumDescriptor {
	return file_rendezvous_proto_enumTypes[4].Descriptor()
}

func (PunchHoleResponse_Failure) Type() protoreflect.EnumType {
	return &file_rendezvous_proto_enumTypes[4]
}

func (x PunchHoleResponse_Failure) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PunchHoleResponse_Failure.Descriptor instead.
func (PunchHoleResponse_Failure) EnumDescriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{10, 0}
}

type RegisterPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Serial        int32                  `protobuf:"varint,2,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPeer) Reset() {
	*x = RegisterPeer{}
	mi := &file_rendezvous_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPeer) ProtoMessage() {}

func (x *RegisterPeer) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPeer.ProtoReflect.Descriptor instead.
func (*RegisterPeer) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterPeer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterPeer) GetSerial() int32 {
	if x != nil {
		return x.Serial
	}
	return 0
}

type RegisterPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestPk     bool                   `protobuf:"varint,2,opt,name=request_pk,json=requestPk,proto3" json:"request_pk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPeerResponse) Reset() {
	*x = RegisterPeerResponse{}
	mi := &file_rendezvous_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPeerResponse) ProtoMessage() {}

func (x *RegisterPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPeerResponse.ProtoReflect.Descriptor instead.
func (*RegisterPeerResponse) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterPeerResponse) GetRequestPk() bool {
	if x != nil {
		return x.RequestPk
	}
	return false
}

type PunchHoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NatType       NatType                `protobuf:"varint,2,opt,name=nat_type,json=natType,proto3,enum=hbb.NatType" json:"nat_type,omitempty"`
	LicenceKey    string                 `protobuf:"bytes,3,opt,name=licence_key,json=licenceKey,proto3" json:"licence_key,omitempty"`
	ConnType      ConnType               `protobuf:"varint,4,opt,name=conn_type,json=connType,proto3,enum=hbb.ConnType" json:"conn_type,omitempty"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	UdpPort       int32                  `protobuf:"varint,7,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"`
	ForceRelay    bool                   `protobuf:"varint,8,opt,name=force_relay,json=forceRelay,proto3" json:"force_relay,omitempty"`
	UpnpPort      int32                  `protobuf:"varint,9,opt,name=upnp_port,json=upnpPort,proto3" json:"upnp_port,omitempty"`
	SocketAddrV6  []byte                 `protobuf:"bytes,10,opt,name=socket_addr_v6,json=socketAddrV6,proto3" json:"socket_addr_v6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PunchHoleRequest) Reset() {
	*x = PunchHoleRequest{}
	mi := &file_rendezvous_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PunchHoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PunchHoleRequest) ProtoMessage() {}

func (x *PunchHoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PunchHoleRequest.ProtoReflect.Descriptor instead.
func (*PunchHoleRequest) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{2}
}

func (x *PunchHoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PunchHoleRequest) GetNatType() NatType {
	if x != nil {
		return x.NatType
	}
	return NatType_UNKNOWN_NAT
}

func (x *PunchHoleRequest) GetLicenceKey() string {
	if x != nil {
		return x.LicenceKey
	}
	return ""
}

func (x *PunchHoleRequest) GetConnType() ConnType {
	if x != nil {
		return x.ConnType
	}
	return ConnType_DEFAULT_CONN
}

func (x *PunchHoleRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PunchHoleRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PunchHoleRequest) GetUdpPort() int32 {
	if x != nil {
		return x.UdpPort
	}
	return 0
}

func (x *PunchHoleRequest) GetForceRelay() bool {
	if x != nil {
		return x.ForceRelay
	}
	return false
}

func (x *PunchHoleRequest) GetUpnpPort() int32 {
	if x != nil {
		return x.UpnpPort
	}
	return 0
}

func (x *PunchHoleRequest) GetSocketAddrV6() []byte {
	if x != nil {
		return x.SocketAddrV6
	}
	return nil
}

type ControlPermissions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   uint64                 `protobuf:"varint,1,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlPermissions) Reset() {
	*x = ControlPermissions{}
	mi := &file_rendezvous_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPermissions) ProtoMessage() {}

func (x *ControlPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlPermissions.ProtoReflect.Descriptor instead.
func (*ControlPermissions) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{3}
}

func (x *ControlPermissions) GetPermissions() uint64 {
	if x != nil {
		return x.Permissions
	}
	return 0
}

type PunchHole struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SocketAddr         []byte                 `protobuf:"bytes,1,opt,name=socket_addr,json=socketAddr,proto3" json:"socket_addr,omitempty"`
	RelayServer        string                 `protobuf:"bytes,2,opt,name=relay_server,json=relayServer,proto3" json:"relay_server,omitempty"`
	NatType            NatType                `protobuf:"varint,3,opt,name=nat_type,json=natType,proto3,enum=hbb.NatType" json:"nat_type,omitempty"`
	UdpPort            int32                  `protobuf:"varint,4,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"`
	ForceRelay         bool                   `protobuf:"varint,5,opt,name=force_relay,json=forceRelay,proto3" json:"force_relay,omitempty"`
	UpnpPort           int32                  `protobuf:"varint,6,opt,name=upnp_port,json=upnpPort,proto3" json:"upnp_port,omitempty"`
	SocketAddrV6       []byte                 `protobuf:"bytes,7,opt,name=socket_addr_v6,json=socketAddrV6,proto3" json:"socket_addr_v6,omitempty"`
	ControlPermissions *ControlPermissions    `protobuf:"bytes,8,opt,name=control_permissions,json=controlPermissions,proto3" json:"control_permissions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PunchHole) Reset() {
	*x = PunchHole{}
	mi := &file_rendezvous_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PunchHole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PunchHole) ProtoMessage() {}

func (x *PunchHole) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PunchHole.ProtoReflect.Descriptor instead.
func (*PunchHole) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{4}
}

func (x *PunchHole) GetSocketAddr() []byte {
	if x != nil {
		return x.SocketAddr
	}
	return nil
}

func (x *PunchHole) GetRelayServer() string {
	if x != nil {
		return x.RelayServer
	}
	return ""
}

func (x *PunchHole) GetNatType() NatType {
	if x != nil {
		return x.NatType
	}
	return NatType_UNKNOWN_NAT
}

func (x *PunchHole) GetUdpPort() int32 {
	if x != nil {
		return x.UdpPort
	}
	return 0
}

func (x *PunchHole) GetForceRelay() bool {
	if x != nil {
		return x.ForceRelay
	}
	return false
}

func (x *PunchHole) GetUpnpPort() int32 {
	if x != nil {
		return x.UpnpPort
	}
	return 0
}

func (x *PunchHole) GetSocketAddrV6() []byte {
	if x != nil {
		return x.SocketAddrV6
	}
	return nil
}

func (x *PunchHole) GetControlPermissions() *ControlPermissions {
	if x != nil {
		return x.ControlPermissions
	}
	return nil
}

type TestNatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serial        int32                  `protobuf:"varint,1,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestNatRequest) Reset() {
	*x = TestNatRequest{}
	mi := &file_rendezvous_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestNatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestNatRequest) ProtoMessage() {}

func (x *TestNatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestNatRequest.ProtoReflect.Descriptor instead.
func (*TestNatRequest) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{5}
}

func (x *TestNatRequest) GetSerial() int32 {
	if x != nil {
		return x.Serial
	}
	return 0
}

type TestNatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Cu            *ConfigUpdate          `protobuf:"bytes,2,opt,name=cu,proto3" json:"cu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestNatResponse) Reset() {
	*x = TestNatResponse{}
	mi := &file_rendezvous_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestNatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestNatResponse) ProtoMessage() {}

func (x *TestNatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestNatResponse.ProtoReflect.Descriptor instead.
func (*TestNatResponse) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{6}
}

func (x *TestNatResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *TestNatResponse) GetCu() *ConfigUpdate {
	if x != nil {
		return x.Cu
	}
	return nil
}

type PunchHoleSent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SocketAddr    []byte                 `protobuf:"bytes,1,opt,name=socket_addr,json=socketAddr,proto3" json:"socket_addr,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	RelayServer   string                 `protobuf:"bytes,3,opt,name=relay_server,json=relayServer,proto3" json:"relay_server,omitempty"`
	NatType       NatType                `protobuf:"varint,4,opt,name=nat_type,json=natType,proto3,enum=hbb.NatType" json:"nat_type,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	UpnpPort      int32                  `protobuf:"varint,6,opt,name=upnp_port,json=upnpPort,proto3" json:"upnp_port,omitempty"`
	SocketAddrV6  []byte                 `protobuf:"bytes,7,opt,name=socket_addr_v6,json=socketAddrV6,proto3" json:"socket_addr_v6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PunchHoleSent) Reset() {
	*x = PunchHoleSent{}
	mi := &file_rendezvous_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PunchHoleSent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PunchHoleSent) ProtoMessage() {}

func (x *PunchHoleSent) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PunchHoleSent.ProtoReflect.Descriptor instead.
func (*PunchHoleSent) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{7}
}

func (x *PunchHoleSent) GetSocketAddr() []byte {
	if x != nil {
		return x.SocketAddr
	}
	return nil
}

func (x *PunchHoleSent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PunchHoleSent) GetRelayServer() string {
	if x != nil {
		return x.RelayServer
	}
	return ""
}

func (x *PunchHoleSent) GetNatType() NatType {
	if x != nil {
		return x.NatType
	}
	return NatType_UNKNOWN_NAT
}

func (x *PunchHoleSent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PunchHoleSent) GetUpnpPort() int32 {
	if x != nil {
		return x.UpnpPort
	}
	return 0
}

func (x *PunchHoleSent) GetSocketAddrV6() []byte {
	if x != nil {
		return x.SocketAddrV6
	}
	return nil
}

type RegisterPk struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid             []byte                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Pk               []byte                 `protobuf:"bytes,3,opt,name=pk,proto3" json:"pk,omitempty"`
	OldId            string                 `protobuf:"bytes,4,opt,name=old_id,json=oldId,proto3" json:"old_id,omitempty"`
	NoRegisterDevice bool                   `protobuf:"varint,5,opt,name=no_register_device,json=noRegisterDevice,proto3" json:"no_register_device,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterPk) Reset() {
	*x = RegisterPk{}
	mi := &file_rendezvous_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPk) ProtoMessage() {}

func (x *RegisterPk) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPk.ProtoReflect.Descriptor instead.
func (*RegisterPk) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterPk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterPk) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *RegisterPk) GetPk() []byte {
	if x != nil {
		return x.Pk
	}
	return nil
}

func (x *RegisterPk) GetOldId() string {
	if x != nil {
		return x.OldId
	}
	return ""
}

func (x *RegisterPk) GetNoRegisterDevice() bool {
	if x != nil {
		return x.NoRegisterDevice
	}
	return false
}

type RegisterPkResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Result        RegisterPkResponse_Result `protobuf:"varint,1,opt,name=result,proto3,enum=hbb.RegisterPkResponse_Result" json:"result,omitempty"`
	KeepAlive     int32                     `protobuf:"varint,2,opt,name=keep_alive,json=keepAlive,proto3" json:"keep_alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPkResponse) Reset() {
	*x = RegisterPkResponse{}
	mi := &file_rendezvous_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPkResponse) ProtoMessage() {}

func (x *RegisterPkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPkResponse.ProtoReflect.Descriptor instead.
func (*RegisterPkResponse) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterPkResponse) GetResult() RegisterPkResponse_Result {
	if x != nil {
		return x.Result
	}
	return RegisterPkResponse_OK
}

func (x *RegisterPkResponse) GetKeepAlive() int32 {
	if x != nil {
		return x.KeepAlive
	}
	return 0
}

type PunchHoleResponse struct {
	state       protoimpl.MessageState    `protogen:"open.v1"`
	SocketAddr  []byte                    `protobuf:"bytes,1,opt,name=socket_addr,json=socketAddr,proto3" json:"socket_addr,omitempty"`
	Pk          []byte                    `protobuf:"bytes,2,opt,name=pk,proto3" json:"pk,omitempty"`
	Failure     PunchHoleResponse_Failure `protobuf:"varint,3,opt,name=failure,proto3,enum=hbb.PunchHoleResponse_Failure" json:"failure,omitempty"`
	RelayServer string                    `protobuf:"bytes,4,opt,name=relay_server,json=relayServer,proto3" json:"relay_server,omitempty"`
	// Types that are valid to be assigned to Union:
	//
	//	*PunchHoleResponse_NatType
	//	*PunchHoleResponse_IsLocal
	Union         isPunchHoleResponse_Union `protobuf_oneof:"union"`
	OtherFailure  string                    `protobuf:"bytes,7,opt,name=other_failure,json=otherFailure,proto3" json:"other_failure,omitempty"`
	Feedback      int32                     `protobuf:"varint,8,opt,name=feedback,proto3" json:"feedback,omitempty"`
	IsUdp         bool                      `protobuf:"varint,9,opt,name=is_udp,json=isUdp,proto3" json:"is_udp,omitempty"`
	UpnpPort      int32                     `protobuf:"varint,10,opt,name=upnp_port,json=upnpPort,proto3" json:"upnp_port,omitempty"`
	SocketAddrV6  []byte                    `protobuf:"bytes,11,opt,name=socket_addr_v6,json=socketAddrV6,proto3" json:"socket_addr_v6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PunchHoleResponse) Reset() {
	*x = PunchHoleResponse{}
	mi := &file_rendezvous_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PunchHoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PunchHoleResponse) ProtoMessage() {}

func (x *PunchHoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PunchHoleResponse.ProtoReflect.Descriptor instead.
func (*PunchHoleResponse) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{10}
}

func (x *PunchHoleResponse) GetSocketAddr() []byte {
	if x != nil {
		return x.SocketAddr
	}
	return nil
}

func (x *PunchHoleResponse) GetPk() []byte {
	if x != nil {
		return x.Pk
	}
	return nil
}

func (x *PunchHoleResponse) GetFailure() PunchHoleResponse_Failure {
	if x != nil {
		return x.Failure
	}
	return PunchHoleResponse_ID_NOT_EXIST
}

func (x *PunchHoleResponse) GetRelayServer() string {
	if x != nil {
		return x.RelayServer
	}
	return ""
}

func (x *PunchHoleResponse) GetUnion() isPunchHoleResponse_Union {
	if x != nil {
		return x.Union
	}
	return nil
}

func (x *PunchHoleResponse) GetNatType() NatType {
	if x != nil {
		if x, ok := x.Union.(*PunchHoleResponse_NatType); ok {
			return x.NatType
		}
	}
	return NatType_UNKNOWN_NAT
}

func (x *PunchHoleResponse) GetIsLocal() bool {
	if x != nil {
		if x, ok := x.Union.(*PunchHoleResponse_IsLocal); ok {
			return x.IsLocal
		}
	}
	return false
}

func (x *PunchHoleResponse) GetOtherFailure() string {
	if x != nil {
		return x.OtherFailure
	}
	return ""
}

func (x *PunchHoleResponse) GetFeedback() int32 {
	if x != nil {
		return x.Feedback
	}
	return 0
}

func (x *PunchHoleResponse) GetIsUdp() bool {
	if x != nil {
		return x.IsUdp
	}
	return false
}

func (x *PunchHoleResponse) GetUpnpPort() int32 {
	if x != nil {
		return x.UpnpPort
	}
	return 0
}

func (x *PunchHoleResponse) GetSocketAddrV6() []byte {
	if x != nil {
		return x.SocketAddrV6
	}
	return nil
}

type isPunchHoleResponse_Union interface {
	isPunchHoleResponse_Union()
}

type PunchHoleResponse_NatType struct {
	NatType NatType `protobuf:"varint,5,opt,name=nat_type,json=natType,proto3,enum=hbb.NatType,oneof"`
}

type PunchHoleResponse_IsLocal struct {
	IsLocal bool `protobuf:"varint,6,opt,name=is_local,json=isLocal,proto3,oneof"`
}

func (*PunchHoleResponse_NatType) isPunchHoleResponse_Union() {}

func (*PunchHoleResponse_IsLocal) isPunchHoleResponse_Union() {}

type ConfigUpdate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Serial            int32                  `protobuf:"varint,1,opt,name=serial,proto3" json:"serial,omitempty"`
	RendezvousServers []string               `protobuf:"bytes,2,rep,name=rendezvous_servers,json=rendezvousServers,proto3" json:"rendezvous_servers,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_rendezvous_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigUpdate) GetSerial() int32 {
	if x != nil {
		return x.Serial
	}
	return 0
}

func (x *ConfigUpdate) GetRendezvousServers() []string {
	if x != nil {
		return x.RendezvousServers
	}
	return nil
}

type RequestRelay struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid               string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SocketAddr         []byte                 `protobuf:"bytes,3,opt,name=socket_addr,json=socketAddr,proto3" json:"socket_addr,omitempty"`
	RelayServer        string                 `protobuf:"bytes,4,opt,name=relay_server,json=relayServer,proto3" json:"relay_server,omitempty"`
	Secure             bool                   `protobuf:"varint,5,opt,name=secure,proto3" json:"secure,omitempty"`
	LicenceKey         string                 `protobuf:"bytes,6,opt,name=licence_key,json=licenceKey,proto3" json:"licence_key,omitempty"`
	ConnType           ConnType               `protobuf:"varint,7,opt,name=conn_type,json=connType,proto3,enum=hbb.ConnType" json:"conn_type,omitempty"`
	Token              string                 `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty"`
	ControlPermissions *ControlPermissions    `protobuf:"bytes,9,opt,name=control_permissions,json=controlPermissions,proto3" json:"control_permissions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RequestRelay) Reset() {
	*x = RequestRelay{}
	mi := &file_rendezvous_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRelay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRelay) ProtoMessage() {}

func (x *RequestRelay) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRelay.ProtoReflect.Descriptor instead.
func (*RequestRelay) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{12}
}

func (x *RequestRelay) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RequestRelay) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RequestRelay) GetSocketAddr() []byte {
	if x != nil {
		return x.SocketAddr
	}
	return nil
}

func (x *RequestRelay) GetRelayServer() string {
	if x != nil {
		return x.RelayServer
	}
	return ""
}

func (x *RequestRelay) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *RequestRelay) GetLicenceKey() string {
	if x != nil {
		return x.LicenceKey
	}
	return ""
}

func (x *RequestRelay) GetConnType() ConnType {
	if x != nil {
		return x.ConnType
	}
	return ConnType_DEFAULT_CONN
}

func (x *RequestRelay) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RequestRelay) GetControlPermissions() *ControlPermissions {
	if x != nil {
		return x.ControlPermissions
	}
	return nil
}

type RelayResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SocketAddr  []byte                 `protobuf:"bytes,1,opt,name=socket_addr,json=socketAddr,proto3" json:"socket_addr,omitempty"`
	Uuid        string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RelayServer string                 `protobuf:"bytes,3,opt,name=relay_server,json=relayServer,proto3" json:"relay_server,omitempty"`
	// Types that are valid to be assigned to Union:
	//
	//	*RelayResponse_Id
	//	*RelayResponse_Pk
	Union         isRelayResponse_Union `protobuf_oneof:"union"`
	RefuseReason  string                `protobuf:"bytes,6,opt,name=refuse_reason,json=refuseReason,proto3" json:"refuse_reason,omitempty"`
	Version       string                `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Feedback      int32                 `protobuf:"varint,9,opt,name=feedback,proto3" json:"feedback,omitempty"`
	SocketAddrV6  []byte                `protobuf:"bytes,10,opt,name=socket_addr_v6,json=socketAddrV6,proto3" json:"socket_addr_v6,omitempty"`
	UpnpPort      int32                 `protobuf:"varint,11,opt,name=upnp_port,json=upnpPort,proto3" json:"upnp_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayResponse) Reset() {
	*x = RelayResponse{}
	mi := &file_rendezvous_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayResponse) ProtoMessage() {}

func (x *RelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayResponse.ProtoReflect.Descriptor instead.
func (*RelayResponse) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{13}
}

func (x *RelayResponse) GetSocketAddr() []byte {
	if x != nil {
		return x.SocketAddr
	}
	return nil
}

func (x *RelayResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RelayResponse) GetRelayServer() string {
	if x != nil {
		return x.RelayServer
	}
	return ""
}

func (x *RelayResponse) GetUnion() isRelayResponse_Union {
	if x != nil {
		return x.Union
	}
	return nil
}

func (x *RelayResponse) GetId() string {
	if x != nil {
		if x, ok := x.Union.(*RelayResponse_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *RelayResponse) GetPk() []byte {
	if x != nil {
		if x, ok := x.Union.(*RelayResponse_Pk); ok {
			return x.Pk
		}
	}
	return nil
}

func (x *RelayResponse) GetRefuseReason() string {
	if x != nil {
		return x.RefuseReason
	}
	return ""
}

func (x *RelayResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RelayResponse) GetFeedback() int32 {
	if x != nil {
		return x.Feedback
	}
	return 0
}

func (x *RelayResponse) GetSocketAddrV6() []byte {
	if x != nil {
		return x.SocketAddrV6
	}
	return nil
}

func (x *RelayResponse) GetUpnpPort() int32 {
	if x != nil {
		return x.UpnpPort
	}
	return 0
}

type isRelayResponse_Union interface {
	isRelayResponse_Union()
}

type RelayResponse_Id struct {
	Id string `protobuf:"bytes,4,opt,name=id,proto3,oneof"`
}

type RelayResponse_Pk struct {
	Pk []byte `protobuf:"bytes,5,opt,name=pk,proto3,oneof"`
}

func (*RelayResponse_Id) isRelayResponse_Union() {}

func (*RelayResponse_Pk) isRelayResponse_Union() {}

type SoftwareUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoftwareUpdate) Reset() {
	*x = SoftwareUpdate{}
	mi := &file_rendezvous_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftwareUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftwareUpdate) ProtoMessage() {}

func (x *SoftwareUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftwareUpdate.ProtoReflect.Descriptor instead.
func (*SoftwareUpdate) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{14}
}

func (x *SoftwareUpdate) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type FetchLocalAddr struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SocketAddr         []byte                 `protobuf:"bytes,1,opt,name=socket_addr,json=socketAddr,proto3" json:"socket_addr,omitempty"`
	RelayServer        string                 `protobuf:"bytes,2,opt,name=relay_server,json=relayServer,proto3" json:"relay_server,omitempty"`
	SocketAddrV6       []byte                 `protobuf:"bytes,3,opt,name=socket_addr_v6,json=socketAddrV6,proto3" json:"socket_addr_v6,omitempty"`
	ControlPermissions *ControlPermissions    `protobuf:"bytes,4,opt,name=control_permissions,json=controlPermissions,proto3" json:"control_permissions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FetchLocalAddr) Reset() {
	*x = FetchLocalAddr{}
	mi := &file_rendezvous_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchLocalAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLocalAddr) ProtoMessage() {}

func (x *FetchLocalAddr) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLocalAddr.ProtoReflect.Descriptor instead.
func (*FetchLocalAddr) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{15}
}

func (x *FetchLocalAddr) GetSocketAddr() []byte {
	if x != nil {
		return x.SocketAddr
	}
	return nil
}

func (x *FetchLocalAddr) GetRelayServer() string {
	if x != nil {
		return x.RelayServer
	}
	return ""
}

func (x *FetchLocalAddr) GetSocketAddrV6() []byte {
	if x != nil {
		return x.SocketAddrV6
	}
	return nil
}

func (x *FetchLocalAddr) GetControlPermissions() *ControlPermissions {
	if x != nil {
		return x.ControlPermissions
	}
	return nil
}

type LocalAddr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SocketAddr    []byte                 `protobuf:"bytes,1,opt,name=socket_addr,json=socketAddr,proto3" json:"socket_addr,omitempty"`
	LocalAddr     []byte                 `protobuf:"bytes,2,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	RelayServer   string                 `protobuf:"bytes,3,opt,name=relay_server,json=relayServer,proto3" json:"relay_server,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	SocketAddrV6  []byte                 `protobuf:"bytes,6,opt,name=socket_addr_v6,json=socketAddrV6,proto3" json:"socket_addr_v6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalAddr) Reset() {
	*x = LocalAddr{}
	mi := &file_rendezvous_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalAddr) ProtoMessage() {}

func (x *LocalAddr) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalAddr.ProtoReflect.Descriptor instead.
func (*LocalAddr) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{16}
}

func (x *LocalAddr) GetSocketAddr() []byte {
	if x != nil {
		return x.SocketAddr
	}
	return nil
}

func (x *LocalAddr) GetLocalAddr() []byte {
	if x != nil {
		return x.LocalAddr
	}
	return nil
}

func (x *LocalAddr) GetRelayServer() string {
	if x != nil {
		return x.RelayServer
	}
	return ""
}

func (x *LocalAddr) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LocalAddr) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LocalAddr) GetSocketAddrV6() []byte {
	if x != nil {
		return x.SocketAddrV6
	}
	return nil
}

type PeerDiscovery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Hostname      string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Platform      string                 `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`
	Misc          string                 `protobuf:"bytes,7,opt,name=misc,proto3" json:"misc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerDiscovery) Reset() {
	*x = PeerDiscovery{}
	mi := &file_rendezvous_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerDiscovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerDiscovery) ProtoMessage() {}

func (x *PeerDiscovery) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerDiscovery.ProtoReflect.Descriptor instead.
func (*PeerDiscovery) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{17}
}

func (x *PeerDiscovery) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *PeerDiscovery) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *PeerDiscovery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PeerDiscovery) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PeerDiscovery) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PeerDiscovery) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PeerDiscovery) GetMisc() string {
	if x != nil {
		return x.Misc
	}
	return ""
}

type OnlineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Peers         []string               `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineRequest) Reset() {
	*x = OnlineRequest{}
	mi := &file_rendezvous_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineRequest) ProtoMessage() {}

func (x *OnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineRequest.ProtoReflect.Descriptor instead.
func (*OnlineRequest) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{18}
}

func (x *OnlineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OnlineRequest) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

type OnlineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	States        []byte                 `protobuf:"bytes,1,opt,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineResponse) Reset() {
	*x = OnlineResponse{}
	mi := &file_rendezvous_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineResponse) ProtoMessage() {}

func (x *OnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineResponse.ProtoReflect.Descriptor instead.
func (*OnlineResponse) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{19}
}

func (x *OnlineResponse) GetStates() []byte {
	if x != nil {
		return x.States
	}
	return nil
}

type KeyExchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          [][]byte               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyExchange) Reset() {
	*x = KeyExchange{}
	mi := &file_rendezvous_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyExchange) ProtoMessage() {}

func (x *KeyExchange) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyExchange.ProtoReflect.Descriptor instead.
func (*KeyExchange) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{20}
}

func (x *KeyExchange) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

type HealthCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_rendezvous_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{21}
}

func (x *HealthCheck) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RendezvousMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Union:
	//
	//	*RendezvousMessage_RegisterPeer
	//	*RendezvousMessage_RegisterPeerResponse
	//	*RendezvousMessage_PunchHoleRequest
	//	*RendezvousMessage_PunchHole
	//	*RendezvousMessage_PunchHoleSent
	//	*RendezvousMessage_PunchHoleResponse
	//	*RendezvousMessage_FetchLocalAddr
	//	*RendezvousMessage_LocalAddr
	//	*RendezvousMessage_ConfigureUpdate
	//	*RendezvousMessage_RegisterPk
	//	*RendezvousMessage_RegisterPkResponse
	//	*RendezvousMessage_SoftwareUpdate
	//	*RendezvousMessage_RequestRelay
	//	*RendezvousMessage_RelayResponse
	//	*RendezvousMessage_TestNatRequest
	//	*RendezvousMessage_TestNatResponse
	//	*RendezvousMessage_PeerDiscovery
	//	*RendezvousMessage_OnlineRequest
	//	*RendezvousMessage_OnlineResponse
	//	*RendezvousMessage_KeyExchange
	//	*RendezvousMessage_Hc
	Union         isRendezvousMessage_Union `protobuf_oneof:"union"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RendezvousMessage) Reset() {
	*x = RendezvousMessage{}
	mi := &file_rendezvous_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RendezvousMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RendezvousMessage) ProtoMessage() {}

func (x *RendezvousMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RendezvousMessage.ProtoReflect.Descriptor instead.
func (*RendezvousMessage) Descriptor() ([]byte, []int) {
	return file_rendezvous_proto_rawDescGZIP(), []int{22}
}

func (x *RendezvousMessage) GetUnion() isRendezvousMessage_Union {
	if x != nil {
		return x.Union
	}
	return nil
}

func (x *RendezvousMessage) GetRegisterPeer() *RegisterPeer {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_RegisterPeer); ok {
			return x.RegisterPeer
		}
	}
	return nil
}

func (x *RendezvousMessage) GetRegisterPeerResponse() *RegisterPeerResponse {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_RegisterPeerResponse); ok {
			return x.RegisterPeerResponse
		}
	}
	return nil
}

func (x *RendezvousMessage) GetPunchHoleRequest() *PunchHoleRequest {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_PunchHoleRequest); ok {
			return x.PunchHoleRequest
		}
	}
	return nil
}

func (x *RendezvousMessage) GetPunchHole() *PunchHole {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_PunchHole); ok {
			return x.PunchHole
		}
	}
	return nil
}

func (x *RendezvousMessage) GetPunchHoleSent() *PunchHoleSent {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_PunchHoleSent); ok {
			return x.PunchHoleSent
		}
	}
	return nil
}

func (x *RendezvousMessage) GetPunchHoleResponse() *PunchHoleResponse {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_PunchHoleResponse); ok {
			return x.PunchHoleResponse
		}
	}
	return nil
}

func (x *RendezvousMessage) GetFetchLocalAddr() *FetchLocalAddr {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_FetchLocalAddr); ok {
			return x.FetchLocalAddr
		}
	}
	return nil
}

func (x *RendezvousMessage) GetLocalAddr() *LocalAddr {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_LocalAddr); ok {
			return x.LocalAddr
		}
	}
	return nil
}

func (x *RendezvousMessage) GetConfigureUpdate() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_ConfigureUpdate); ok {
			return x.ConfigureUpdate
		}
	}
	return nil
}

func (x *RendezvousMessage) GetRegisterPk() *RegisterPk {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_RegisterPk); ok {
			return x.RegisterPk
		}
	}
	return nil
}

func (x *RendezvousMessage) GetRegisterPkResponse() *RegisterPkResponse {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_RegisterPkResponse); ok {
			return x.RegisterPkResponse
		}
	}
	return nil
}

func (x *RendezvousMessage) GetSoftwareUpdate() *SoftwareUpdate {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_SoftwareUpdate); ok {
			return x.SoftwareUpdate
		}
	}
	return nil
}

func (x *RendezvousMessage) GetRequestRelay() *RequestRelay {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_RequestRelay); ok {
			return x.RequestRelay
		}
	}
	return nil
}

func (x *RendezvousMessage) GetRelayResponse() *RelayResponse {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_RelayResponse); ok {
			return x.RelayResponse
		}
	}
	return nil
}

func (x *RendezvousMessage) GetTestNatRequest() *TestNatRequest {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_TestNatRequest); ok {
			return x.TestNatRequest
		}
	}
	return nil
}

func (x *RendezvousMessage) GetTestNatResponse() *TestNatResponse {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_TestNatResponse); ok {
			return x.TestNatResponse
		}
	}
	return nil
}

func (x *RendezvousMessage) GetPeerDiscovery() *PeerDiscovery {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_PeerDiscovery); ok {
			return x.PeerDiscovery
		}
	}
	return nil
}

func (x *RendezvousMessage) GetOnlineRequest() *OnlineRequest {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_OnlineRequest); ok {
			return x.OnlineRequest
		}
	}
	return nil
}

func (x *RendezvousMessage) GetOnlineResponse() *OnlineResponse {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_OnlineResponse); ok {
			return x.OnlineResponse
		}
	}
	return nil
}

func (x *RendezvousMessage) GetKeyExchange() *KeyExchange {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_KeyExchange); ok {
			return x.KeyExchange
		}
	}
	return nil
}

func (x *RendezvousMessage) GetHc() *HealthCheck {
	if x != nil {
		if x, ok := x.Union.(*RendezvousMessage_Hc); ok {
			return x.Hc
		}
	}
	return nil
}

type isRendezvousMessage_Union interface {
	isRendezvousMessage_Union()
}

type RendezvousMessage_RegisterPeer struct {
	RegisterPeer *RegisterPeer `protobuf:"bytes,6,opt,name=register_peer,json=registerPeer,proto3,oneof"`
}

type RendezvousMessage_RegisterPeerResponse struct {
	RegisterPeerResponse *RegisterPeerResponse `protobuf:"bytes,7,opt,name=register_peer_response,json=registerPeerResponse,proto3,oneof"`
}

type RendezvousMessage_PunchHoleRequest struct {
	PunchHoleRequest *PunchHoleRequest `protobuf:"bytes,8,opt,name=punch_hole_request,json=punchHoleRequest,proto3,oneof"`
}

type RendezvousMessage_PunchHole struct {
	PunchHole *PunchHole `protobuf:"bytes,9,opt,name=punch_hole,json=punchHole,proto3,oneof"`
}

type RendezvousMessage_PunchHoleSent struct {
	PunchHoleSent *PunchHoleSent `protobuf:"bytes,10,opt,name=punch_hole_sent,json=punchHoleSent,proto3,oneof"`
}

type RendezvousMessage_PunchHoleResponse struct {
	PunchHoleResponse *PunchHoleResponse `protobuf:"bytes,11,opt,name=punch_hole_response,json=punchHoleResponse,proto3,oneof"`
}

type RendezvousMessage_FetchLocalAddr struct {
	FetchLocalAddr *FetchLocalAddr `protobuf:"bytes,12,opt,name=fetch_local_addr,json=fetchLocalAddr,proto3,oneof"`
}

type RendezvousMessage_LocalAddr struct {
	LocalAddr *LocalAddr `protobuf:"bytes,13,opt,name=local_addr,json=localAddr,proto3,oneof"`
}

type RendezvousMessage_ConfigureUpdate struct {
	ConfigureUpdate *ConfigUpdate `protobuf:"bytes,14,opt,name=configure_update,json=configureUpdate,proto3,oneof"`
}

type RendezvousMessage_RegisterPk struct {
	RegisterPk *RegisterPk `protobuf:"bytes,15,opt,name=register_pk,json=registerPk,proto3,oneof"`
}

type RendezvousMessage_RegisterPkResponse struct {
	RegisterPkResponse *RegisterPkResponse `protobuf:"bytes,16,opt,name=register_pk_response,json=registerPkResponse,proto3,oneof"`
}

type RendezvousMessage_SoftwareUpdate struct {
	SoftwareUpdate *SoftwareUpdate `protobuf:"bytes,17,opt,name=software_update,json=softwareUpdate,proto3,oneof"`
}

type RendezvousMessage_RequestRelay struct {
	RequestRelay *RequestRelay `protobuf:"bytes,18,opt,name=request_relay,json=requestRelay,proto3,oneof"`
}

type RendezvousMessage_RelayResponse struct {
	RelayResponse *RelayResponse `protobuf:"bytes,19,opt,name=relay_response,json=relayResponse,proto3,oneof"`
}

type RendezvousMessage_TestNatRequest struct {
	TestNatRequest *TestNatRequest `protobuf:"bytes,20,opt,name=test_nat_request,json=testNatRequest,proto3,oneof"`
}

type RendezvousMessage_TestNatResponse struct {
	TestNatResponse *TestNatResponse `protobuf:"bytes,21,opt,name=test_nat_response,json=testNatResponse,proto3,oneof"`
}

type RendezvousMessage_PeerDiscovery struct {
	PeerDiscovery *PeerDiscovery `protobuf:"bytes,22,opt,name=peer_discovery,json=peerDiscovery,proto3,oneof"`
}

type RendezvousMessage_OnlineRequest struct {
	OnlineRequest *OnlineRequest `protobuf:"bytes,23,opt,name=online_request,json=onlineRequest,proto3,oneof"`
}

type RendezvousMessage_OnlineResponse struct {
	OnlineResponse *OnlineResponse `protobuf:"bytes,24,opt,name=online_response,json=onlineResponse,proto3,oneof"`
}

type RendezvousMessage_KeyExchange struct {
	KeyExchange *KeyExchange `protobuf:"bytes,25,opt,name=key_exchange,json=keyExchange,proto3,oneof"`
}

type RendezvousMessage_Hc struct {
	Hc *HealthCheck `protobuf:"bytes,26,opt,name=hc,proto3,oneof"`
}

func (*RendezvousMessage_RegisterPeer) isRendezvousMessage_Union() {}

func (*RendezvousMessage_RegisterPeerResponse) isRendezvousMessage_Union() {}

func (*RendezvousMessage_PunchHoleRequest) isRendezvousMessage_Union() {}

func (*RendezvousMessage_PunchHole) isRendezvousMessage_Union() {}

func (*RendezvousMessage_PunchHoleSent) isRendezvousMessage_Union() {}

func (*RendezvousMessage_PunchHoleResponse) isRendezvousMessage_Union() {}

func (*RendezvousMessage_FetchLocalAddr) isRendezvousMessage_Union() {}

func (*RendezvousMessage_LocalAddr) isRendezvousMessage_Union() {}

func (*RendezvousMessage_ConfigureUpdate) isRendezvousMessage_Union() {}

func (*RendezvousMessage_RegisterPk) isRendezvousMessage_Union() {}

func (*RendezvousMessage_RegisterPkResponse) isRendezvousMessage_Union() {}

func (*RendezvousMessage_SoftwareUpdate) isRendezvousMessage_Union() {}

func (*RendezvousMessage_RequestRelay) isRendezvousMessage_Union() {}

func (*RendezvousMessage_RelayResponse) isRendezvousMessage_Union() {}

func (*RendezvousMessage_TestNatRequest) isRendezvousMessage_Union() {}

func (*RendezvousMessage_TestNatResponse) isRendezvousMessage_Union() {}

func (*RendezvousMessage_PeerDiscovery) isRendezvousMessage_Union() {}

func (*RendezvousMessage_OnlineRequest) isRendezvousMessage_Union() {}

func (*RendezvousMessage_OnlineResponse) isRendezvousMessage_Union() {}

func (*RendezvousMessage_KeyExchange) isRendezvousMessage_Union() {}

func (*RendezvousMessage_Hc) isRendezvousMessage_Union() {}

var File_rendezvous_proto protoreflect.FileDescriptor

const file_rendezvous_proto_rawDesc = "" +
	"\n" +
	"\x10rendezvous.proto\x12\x03hbb\"6\n" +
	"\fRegisterPeer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\x05R\x06serial\"5\n" +
	"\x14RegisterPeerResponse\x12\x1d\n" +
	"\n" +
	"request_pk\x18\x02 \x01(\bR\trequestPk\"\xc7\x02\n" +
	"\x10PunchHoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\bnat_type\x18\x02 \x01(\x0e2\f.hbb.NatTypeR\anatType\x12\x1f\n" +
	"\vlicence_key\x18\x03 \x01(\tR\n" +
	"licenceKey\x12*\n" +
	"\tconn_type\x18\x04 \x01(\x0e2\r.hbb.ConnTypeR\bconnType\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x19\n" +
	"\budp_port\x18\a \x01(\x05R\audpPort\x12\x1f\n" +
	"\vforce_relay\x18\b \x01(\bR\n" +
	"forceRelay\x12\x1b\n" +
	"\tupnp_port\x18\t \x01(\x05R\bupnpPort\x12$\n" +
	"\x0esocket_addr_v6\x18\n" +
	" \x01(\fR\fsocketAddrV6\"\xf1\x01\n" +
	"\x12ControlPermissions\x12 \n" +
	"\vpermissions\x18\x01 \x01(\x04R\vpermissions\"\xb8\x01\n" +
	"\n" +
	"Permission\x12\f\n" +
	"\bkeyboard\x10\x00\x12\x12\n" +
	"\x0eremote_printer\x10\x01\x12\r\n" +
	"\tclipboard\x10\x02\x12\b\n" +
	"\x04file\x10\x03\x12\t\n" +
	"\x05audio\x10\x04\x12\n" +
	"\n" +
	"\x06camera\x10\x05\x12\f\n" +
	"\bterminal\x10\x06\x12\n" +
	"\n" +
	"\x06tunnel\x10\a\x12\v\n" +
	"\arestart\x10\b\x12\r\n" +
	"\trecording\x10\t\x12\x0f\n" +
	"\vblock_input\x10\n" +
	"\x12\x11\n" +
	"\rremote_modify\x10\v\"\xc1\x02\n" +
	"\tPunchHole\x12\x1f\n" +
	"\vsocket_addr\x18\x01 \x01(\fR\n" +
	"socketAddr\x12!\n" +
	"\frelay_server\x18\x02 \x01(\tR\vrelayServer\x12'\n" +
	"\bnat_type\x18\x03 \x01(\x0e2\f.hbb.NatTypeR\anatType\x12\x19\n" +
	"\budp_port\x18\x04 \x01(\x05R\audpPort\x12\x1f\n" +
	"\vforce_relay\x18\x05 \x01(\bR\n" +
	"forceRelay\x12\x1b\n" +
	"\tupnp_port\x18\x06 \x01(\x05R\bupnpPort\x12$\n" +
	"\x0esocket_addr_v6\x18\a \x01(\fR\fsocketAddrV6\x12H\n" +
	"\x13control_permissions\x18\b \x01(\v2\x17.hbb.ControlPermissionsR\x12controlPermissions\"(\n" +
	"\x0eTestNatRequest\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\x05R\x06serial\"H\n" +
	"\x0fTestNatResponse\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12!\n" +
	"\x02cu\x18\x02 \x01(\v2\x11.hbb.ConfigUpdateR\x02cu\"\xe9\x01\n" +
	"\rPunchHoleSent\x12\x1f\n" +
	"\vsocket_addr\x18\x01 \x01(\fR\n" +
	"socketAddr\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12!\n" +
	"\frelay_server\x18\x03 \x01(\tR\vrelayServer\x12'\n" +
	"\bnat_type\x18\x04 \x01(\x0e2\f.hbb.NatTypeR\anatType\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x1b\n" +
	"\tupnp_port\x18\x06 \x01(\x05R\bupnpPort\x12$\n" +
	"\x0esocket_addr_v6\x18\a \x01(\fR\fsocketAddrV6\"\x85\x01\n" +
	"\n" +
	"RegisterPk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\fR\x04uuid\x12\x0e\n" +
	"\x02pk\x18\x03 \x01(\fR\x02pk\x12\x15\n" +
	"\x06old_id\x18\x04 \x01(\tR\x05oldId\x12,\n" +
	"\x12no_register_device\x18\x05 \x01(\bR\x10noRegisterDevice\"\xeb\x01\n" +
	"\x12RegisterPkResponse\x126\n" +
	"\x06result\x18\x01 \x01(\x0e2\x1e.hbb.RegisterPkResponse.ResultR\x06result\x12\x1d\n" +
	"\n" +
	"keep_alive\x18\x02 \x01(\x05R\tkeepAlive\"~\n" +
	"\x06Result\x12\x06\n" +
	"\x02OK\x10\x00\x12\x11\n" +
	"\rUUID_MISMATCH\x10\x02\x12\r\n" +
	"\tID_EXISTS\x10\x03\x12\x10\n" +
	"\fTOO_FREQUENT\x10\x04\x12\x15\n" +
	"\x11INVALID_ID_FORMAT\x10\x05\x12\x0f\n" +
	"\vNOT_SUPPORT\x10\x06\x12\x10\n" +
	"\fSERVER_ERROR\x10\a\"\xe2\x03\n" +
	"\x11PunchHoleResponse\x12\x1f\n" +
	"\vsocket_addr\x18\x01 \x01(\fR\n" +
	"socketAddr\x12\x0e\n" +
	"\x02pk\x18\x02 \x01(\fR\x02pk\x128\n" +
	"\afailure\x18\x03 \x01(\x0e2\x1e.hbb.PunchHoleResponse.FailureR\afailure\x12!\n" +
	"\frelay_server\x18\x04 \x01(\tR\vrelayServer\x12)\n" +
	"\bnat_type\x18\x05 \x01(\x0e2\f.hbb.NatTypeH\x00R\anatType\x12\x1b\n" +
	"\bis_local\x18\x06 \x01(\bH\x00R\aisLocal\x12#\n" +
	"\rother_failure\x18\a \x01(\tR\fotherFailure\x12\x1a\n" +
	"\bfeedback\x18\b \x01(\x05R\bfeedback\x12\x15\n" +
	"\x06is_udp\x18\t \x01(\bR\x05isUdp\x12\x1b\n" +
	"\tupnp_port\x18\n" +
	" \x01(\x05R\bupnpPort\x12$\n" +
	"\x0esocket_addr_v6\x18\v \x01(\fR\fsocketAddrV6\"S\n" +
	"\aFailure\x12\x10\n" +
	"\fID_NOT_EXIST\x10\x00\x12\v\n" +
	"\aOFFLINE\x10\x02\x12\x14\n" +
	"\x10LICENSE_MISMATCH\x10\x03\x12\x13\n" +
	"\x0fLICENSE_OVERUSE\x10\x04B\a\n" +
	"\x05union\"U\n" +
	"\fConfigUpdate\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\x05R\x06serial\x12-\n" +
	"\x12rendezvous_servers\x18\x02 \x03(\tR\x11rendezvousServers\"\xbb\x02\n" +
	"\fRequestRelay\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vsocket_addr\x18\x03 \x01(\fR\n" +
	"socketAddr\x12!\n" +
	"\frelay_server\x18\x04 \x01(\tR\vrelayServer\x12\x16\n" +
	"\x06secure\x18\x05 \x01(\bR\x06secure\x12\x1f\n" +
	"\vlicence_key\x18\x06 \x01(\tR\n" +
	"licenceKey\x12*\n" +
	"\tconn_type\x18\a \x01(\x0e2\r.hbb.ConnTypeR\bconnType\x12\x14\n" +
	"\x05token\x18\b \x01(\tR\x05token\x12H\n" +
	"\x13control_permissions\x18\t \x01(\v2\x17.hbb.ControlPermissionsR\x12controlPermissions\"\xb2\x02\n" +
	"\rRelayResponse\x12\x1f\n" +
	"\vsocket_addr\x18\x01 \x01(\fR\n" +
	"socketAddr\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12!\n" +
	"\frelay_server\x18\x03 \x01(\tR\vrelayServer\x12\x10\n" +
	"\x02id\x18\x04 \x01(\tH\x00R\x02id\x12\x10\n" +
	"\x02pk\x18\x05 \x01(\fH\x00R\x02pk\x12#\n" +
	"\rrefuse_reason\x18\x06 \x01(\tR\frefuseReason\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x12\x1a\n" +
	"\bfeedback\x18\t \x01(\x05R\bfeedback\x12$\n" +
	"\x0esocket_addr_v6\x18\n" +
	" \x01(\fR\fsocketAddrV6\x12\x1b\n" +
	"\tupnp_port\x18\v \x01(\x05R\bupnpPortB\a\n" +
	"\x05union\"\"\n" +
	"\x0eSoftwareUpdate\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xc4\x01\n" +
	"\x0eFetchLocalAddr\x12\x1f\n" +
	"\vsocket_addr\x18\x01 \x01(\fR\n" +
	"socketAddr\x12!\n" +
	"\frelay_server\x18\x02 \x01(\tR\vrelayServer\x12$\n" +
	"\x0esocket_addr_v6\x18\x03 \x01(\fR\fsocketAddrV6\x12H\n" +
	"\x13control_permissions\x18\x04 \x01(\v2\x17.hbb.ControlPermissionsR\x12controlPermissions\"\xbe\x01\n" +
	"\tLocalAddr\x12\x1f\n" +
	"\vsocket_addr\x18\x01 \x01(\fR\n" +
	"socketAddr\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x02 \x01(\fR\tlocalAddr\x12!\n" +
	"\frelay_server\x18\x03 \x01(\tR\vrelayServer\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12$\n" +
	"\x0esocket_addr_v6\x18\x06 \x01(\fR\fsocketAddrV6\"\xab\x01\n" +
	"\rPeerDiscovery\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\tR\bplatform\x12\x12\n" +
	"\x04misc\x18\a \x01(\tR\x04misc\"5\n" +
	"\rOnlineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05peers\x18\x02 \x03(\tR\x05peers\"(\n" +
	"\x0eOnlineResponse\x12\x16\n" +
	"\x06states\x18\x01 \x01(\fR\x06states\"!\n" +
	"\vKeyExchange\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\fR\x04keys\"#\n" +
	"\vHealthCheck\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xad\n" +
	"\n" +
	"\x11RendezvousMessage\x128\n" +
	"\rregister_peer\x18\x06 \x01(\v2\x11.hbb.RegisterPeerH\x00R\fregisterPeer\x12Q\n" +
	"\x16register_peer_response\x18\a \x01(\v2\x19.hbb.RegisterPeerResponseH\x00R\x14registerPeerResponse\x12E\n" +
	"\x12punch_hole_request\x18\b \x01(\v2\x15.hbb.PunchHoleRequestH\x00R\x10punchHoleRequest\x12/\n" +
	"\n" +
	"punch_hole\x18\t \x01(\v2\x0e.hbb.PunchHoleH\x00R\tpunchHole\x12<\n" +
	"\x0fpunch_hole_sent\x18\n" +
	" \x01(\v2\x12.hbb.PunchHoleSentH\x00R\rpunchHoleSent\x12H\n" +
	"\x13punch_hole_response\x18\v \x01(\v2\x16.hbb.PunchHoleResponseH\x00R\x11punchHoleResponse\x12?\n" +
	"\x10fetch_local_addr\x18\f \x01(\v2\x13.hbb.FetchLocalAddrH\x00R\x0efetchLocalAddr\x12/\n" +
	"\n" +
	"local_addr\x18\r \x01(\v2\x0e.hbb.LocalAddrH\x00R\tlocalAddr\x12>\n" +
	"\x10configure_update\x18\x0e \x01(\v2\x11.hbb.ConfigUpdateH\x00R\x0fconfigureUpdate\x122\n" +
	"\vregister_pk\x18\x0f \x01(\v2\x0f.hbb.RegisterPkH\x00R\n" +
	"registerPk\x12K\n" +
	"\x14register_pk_response\x18\x10 \x01(\v2\x17.hbb.RegisterPkResponseH\x00R\x12registerPkResponse\x12>\n" +
	"\x0fsoftware_update\x18\x11 \x01(\v2\x13.hbb.SoftwareUpdateH\x00R\x0esoftwareUpdate\x128\n" +
	"\rrequest_relay\x18\x12 \x01(\v2\x11.hbb.RequestRelayH\x00R\frequestRelay\x12;\n" +
	"\x0erelay_response\x18\x13 \x01(\v2\x12.hbb.RelayResponseH\x00R\rrelayResponse\x12?\n" +
	"\x10test_nat_request\x18\x14 \x01(\v2\x13.hbb.TestNatRequestH\x00R\x0etestNatRequest\x12B\n" +
	"\x11test_nat_response\x18\x15 \x01(\v2\x14.hbb.TestNatResponseH\x00R\x0ftestNatResponse\x12;\n" +
	"\x0epeer_discovery\x18\x16 \x01(\v2\x12.hbb.PeerDiscoveryH\x00R\rpeerDiscovery\x12;\n" +
	"\x0eonline_request\x18\x17 \x01(\v2\x12.hbb.OnlineRequestH\x00R\ronlineRequest\x12>\n" +
	"\x0fonline_response\x18\x18 \x01(\v2\x13.hbb.OnlineResponseH\x00R\x0eonlineResponse\x125\n" +
	"\fkey_exchange\x18\x19 \x01(\v2\x10.hbb.KeyExchangeH\x00R\vkeyExchange\x12\"\n" +
	"\x02hc\x18\x1a \x01(\v2\x10.hbb.HealthCheckH\x00R\x02hcB\a\n" +
	"\x05union*i\n" +
	"\bConnType\x12\x10\n" +
	"\fDEFAULT_CONN\x10\x00\x12\x11\n" +
	"\rFILE_TRANSFER\x10\x01\x12\x10\n" +
	"\fPORT_FORWARD\x10\x02\x12\a\n" +
	"\x03RDP\x10\x03\x12\x0f\n" +
	"\vVIEW_CAMERA\x10\x04\x12\f\n" +
	"\bTERMINAL\x10\x05*9\n" +
	"\aNatType\x12\x0f\n" +
	"\vUNKNOWN_NAT\x10\x00\x12\x0e\n" +
	"\n" +
	"ASYMMETRIC\x10\x01\x12\r\n" +
	"\tSYMMETRIC\x10\x02B.Z,github.com/unitronix/betterdesk-server/protob\x06proto3"

var (
	file_rendezvous_proto_rawDescOnce sync.Once
	file_rendezvous_proto_rawDescData []byte
)

func file_rendezvous_proto_rawDescGZIP() []byte {
	file_rendezvous_proto_rawDescOnce.Do(func() {
		file_rendezvous_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rendezvous_proto_rawDesc), len(file_rendezvous_proto_rawDesc)))
	})
	return file_rendezvous_proto_rawDescData
}

var file_rendezvous_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_rendezvous_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_rendezvous_proto_goTypes = []any{
	(ConnType)(0),                      // 0: hbb.ConnType
	(NatType)(0),                       // 1: hbb.NatType
	(ControlPermissions_Permission)(0), // 2: hbb.ControlPermissions.Permission
	(RegisterPkResponse_Result)(0),     // 3: hbb.RegisterPkResponse.Result
	(PunchHoleResponse_Failure)(0),     // 4: hbb.PunchHoleResponse.Failure
	(*RegisterPeer)(nil),               // 5: hbb.RegisterPeer
	(*RegisterPeerResponse)(nil),       // 6: hbb.RegisterPeerResponse
	(*PunchHoleRequest)(nil),           // 7: hbb.PunchHoleRequest
	(*ControlPermissions)(nil),         // 8: hbb.ControlPermissions
	(*PunchHole)(nil),                  // 9: hbb.PunchHole
	(*TestNatRequest)(nil),             // 10: hbb.TestNatRequest
	(*TestNatResponse)(nil),            // 11: hbb.TestNatResponse
	(*PunchHoleSent)(nil),              // 12: hbb.PunchHoleSent
	(*RegisterPk)(nil),                 // 13: hbb.RegisterPk
	(*RegisterPkResponse)(nil),         // 14: hbb.RegisterPkResponse
	(*PunchHoleResponse)(nil),          // 15: hbb.PunchHoleResponse
	(*ConfigUpdate)(nil),               // 16: hbb.ConfigUpdate
	(*RequestRelay)(nil),               // 17: hbb.RequestRelay
	(*RelayResponse)(nil),              // 18: hbb.RelayResponse
	(*SoftwareUpdate)(nil),             // 19: hbb.SoftwareUpdate
	(*FetchLocalAddr)(nil),             // 20: hbb.FetchLocalAddr
	(*LocalAddr)(nil),                  // 21: hbb.LocalAddr
	(*PeerDiscovery)(nil),              // 22: hbb.PeerDiscovery
	(*OnlineRequest)(nil),              // 23: hbb.OnlineRequest
	(*OnlineResponse)(nil),             // 24: hbb.OnlineResponse
	(*KeyExchange)(nil),                // 25: hbb.KeyExchange
	(*HealthCheck)(nil),                // 26: hbb.HealthCheck
	(*RendezvousMessage)(nil),          // 27: hbb.RendezvousMessage
}
var file_rendezvous_proto_depIdxs = []int32{
	1,  // 0: hbb.PunchHoleRequest.nat_type:type_name -> hbb.NatType
	0,  // 1: hbb.PunchHoleRequest.conn_type:type_name -> hbb.ConnType
	1,  // 2: hbb.PunchHole.nat_type:type_name -> hbb.NatType
	8,  // 3: hbb.PunchHole.control_permissions:type_name -> hbb.ControlPermissions
	16, // 4: hbb.TestNatResponse.cu:type_name -> hbb.ConfigUpdate
	1,  // 5: hbb.PunchHoleSent.nat_type:type_name -> hbb.NatType
	3,  // 6: hbb.RegisterPkResponse.result:type_name -> hbb.RegisterPkResponse.Result
	4,  // 7: hbb.PunchHoleResponse.failure:type_name -> hbb.PunchHoleResponse.Failure
	1,  // 8: hbb.PunchHoleResponse.nat_type:type_name -> hbb.NatType
	0,  // 9: hbb.RequestRelay.conn_type:type_name -> hbb.ConnType
	8,  // 10: hbb.RequestRelay.control_permissions:type_name -> hbb.ControlPermissions
	8,  // 11: hbb.FetchLocalAddr.control_permissions:type_name -> hbb.ControlPermissions
	5,  // 12: hbb.RendezvousMessage.register_peer:type_name -> hbb.RegisterPeer
	6,  // 13: hbb.RendezvousMessage.register_peer_response:type_name -> hbb.RegisterPeerResponse
	7,  // 14: hbb.RendezvousMessage.punch_hole_request:type_name -> hbb.PunchHoleRequest
	9,  // 15: hbb.RendezvousMessage.punch_hole:type_name -> hbb.PunchHole
	12, // 16: hbb.RendezvousMessage.punch_hole_sent:type_name -> hbb.PunchHoleSent
	15, // 17: hbb.RendezvousMessage.punch_hole_response:type_name -> hbb.PunchHoleResponse
	20, // 18: hbb.RendezvousMessage.fetch_local_addr:type_name -> hbb.FetchLocalAddr
	21, // 19: hbb.RendezvousMessage.local_addr:type_name -> hbb.LocalAddr
	16, // 20: hbb.RendezvousMessage.configure_update:type_name -> hbb.ConfigUpdate
	13, // 21: hbb.RendezvousMessage.register_pk:type_name -> hbb.RegisterPk
	14, // 22: hbb.RendezvousMessage.register_pk_response:type_name -> hbb.RegisterPkResponse
	19, // 23: hbb.RendezvousMessage.software_update:type_name -> hbb.SoftwareUpdate
	17, // 24: hbb.RendezvousMessage.request_relay:type_name -> hbb.RequestRelay
	18, // 25: hbb.RendezvousMessage.relay_response:type_name -> hbb.RelayResponse
	10, // 26: hbb.RendezvousMessage.test_nat_request:type_name -> hbb.TestNatRequest
	11, // 27: hbb.RendezvousMessage.test_nat_response:type_name -> hbb.TestNatResponse
	22, // 28: hbb.RendezvousMessage.peer_discovery:type_name -> hbb.PeerDiscovery
	23, // 29: hbb.RendezvousMessage.online_request:type_name -> hbb.OnlineRequest
	24, // 30: hbb.RendezvousMessage.online_response:type_name -> hbb.OnlineResponse
	25, // 31: hbb.RendezvousMessage.key_exchange:type_name -> hbb.KeyExchange
	26, // 32: hbb.RendezvousMessage.hc:type_name -> hbb.HealthCheck
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_rendezvous_proto_init() }
func file_rendezvous_proto_init() {
	if File_rendezvous_proto != nil {
		return
	}
	file_rendezvous_proto_msgTypes[10].OneofWrappers = []any{
		(*PunchHoleResponse_NatType)(nil),
		(*PunchHoleResponse_IsLocal)(nil),
	}
	file_rendezvous_proto_msgTypes[13].OneofWrappers = []any{
		(*RelayResponse_Id)(nil),
		(*RelayResponse_Pk)(nil),
	}
	file_rendezvous_proto_msgTypes[22].OneofWrappers = []any{
		(*RendezvousMessage_RegisterPeer)(nil),
		(*RendezvousMessage_RegisterPeerResponse)(nil),
		(*RendezvousMessage_PunchHoleRequest)(nil),
		(*RendezvousMessage_PunchHole)(nil),
		(*RendezvousMessage_PunchHoleSent)(nil),
		(*RendezvousMessage_PunchHoleResponse)(nil),
		(*RendezvousMessage_FetchLocalAddr)(nil),
		(*RendezvousMessage_LocalAddr)(nil),
		(*RendezvousMessage_ConfigureUpdate)(nil),
		(*RendezvousMessage_RegisterPk)(nil),
		(*RendezvousMessage_RegisterPkResponse)(nil),
		(*RendezvousMessage_SoftwareUpdate)(nil),
		(*RendezvousMessage_RequestRelay)(nil),
		(*RendezvousMessage_RelayResponse)(nil),
		(*RendezvousMessage_TestNatRequest)(nil),
		(*RendezvousMessage_TestNatResponse)(nil),
		(*RendezvousMessage_PeerDiscovery)(nil),
		(*RendezvousMessage_OnlineRequest)(nil),
		(*RendezvousMessage_OnlineResponse)(nil),
		(*RendezvousMessage_KeyExchange)(nil),
		(*RendezvousMessage_Hc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rendezvous_proto_rawDesc), len(file_rendezvous_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rendezvous_proto_goTypes,
		DependencyIndexes: file_rendezvous_proto_depIdxs,
		EnumInfos:         file_rendezvous_proto_enumTypes,
		MessageInfos:      file_rendezvous_proto_msgTypes,
	}.Build()
	File_rendezvous_proto = out.File
	file_rendezvous_proto_goTypes = nil
	file_rendezvous_proto_depIdxs = nil
}
